### ISSUE TITLE
Errors in methods during compilation

### ISSUE THREAD

**Issue by lavstudia** [RoadTurtleGames/ArchGodotEntityDebugger#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'TreeItem' does not contain a definition for 'CreateOrGetChild' and no accessible extension method 'CreateOrGetChild' accepting a first argument of type 'TreeItem' could be found (are you missing a using directive or an assembly reference?)	...\addons\Arch Entity Debugger\Scripts\EntityTreeRendering.cs	48	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'TreeItem' does not contain a definition for 'CreateChildAlphabetically' and no accessible extension method 'CreateChildAlphabetically' accepting a first argument of type 'TreeItem' could be found (are you missing a using directive or an assembly reference?)	...\addons\Arch Entity Debugger\Scripts\EntityDebugger.cs	214	Active

**Comment by richdog** [comment]
Good catch, I forgot a copy a script into the addon. I've just pushed up a fix, let me know if there are any other issues!

**Comment by lavstudia** [comment]
Thanks for the quick solution!
