### ISSUE TITLE
The addon uses dependencies from RoadTurtleGames

### ISSUE THREAD

**Issue by lavstudia** [RoadTurtleGames/ArchGodotEntityDebugger#2]
Severity Code Description Project File Line Suppression State
Error CS0234 The type or namespace name 'Logging' does not exist in the namespace 'RoadTurtleGames' (are you missing an assembly reference?) ...\addons\Arch Entity Debugger\Scripts\EntityTreeRendering.cs 4 Active

**Comment by richdog** [comment]
I fixed this as well in the same commit as #3
