### ISSUE TITLE
Load Error - resource file NotoSans-Bold.ttf

### ISSUE THREAD

**Issue by lavstudia** [RoadTurtleGames/ArchGodotEntityDebugger#3]
![Screenshot_30](https://github.com/RoadTurtleGames/ArchGodotEntityDebugger/assets/2664222/34f8b715-c59b-4c9f-a2cc-f4f3c218ca4e)

**Comment by richdog** [comment]
Ahh, I should have tested this in a new project it seems. Thanks again, will fix shortly.

**Comment by richdog** [comment]
Alright, give it another spin, this time I tested in a standalone project so it should work.

**Comment by lavstudia** [comment]
Thank you for the great addon!
